services:
    orderproduct_controller:
        class: Stanhome\OrderBundle\Controller\OrderProductController
#    stanhome_order.example:
#        class: Stanhome\OrderBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
