domiGestion_rh_customer_client:
    path: /client
    defaults:
        _controller: DomiGestionRhBundle:Customer:listClient

domiGestion_rh_customer_hostess:
    path: /hostess
    defaults:
        _controller: DomiGestionRhBundle:Customer:listHostess

domiGestion_rh_customer_add:
    path: /add
    defaults:
        _controller: DomiGestionRhBundle:Customer:add

stanhome_rh_customer_show:
    path: /show/{id}
    methods: [GET]
    defaults:
        _controller: DomiGestionRhBundle:Customer:show

domiGestion_rh_customer_edit:
    path: /edit/{id}
    defaults:
        _controller: DomiGestionRhBundle:Customer:edit

stanhome_rh_customer_update:
    path: /update/{id}
    methods: [POST]
    defaults:
        _controller: DomiGestionRhBundle:Customer:update

domiGestion_rh_customer_delete:
    path: /delete/{id}
    methods: [GET]
    defaults:
        _controller: DomiGestionRhBundle:Customer:delete
