domiGestion_rh_customer_client:
    path: /client
    defaults:
        _controller: DomiGestionRhBundle:Customer:listClient

domiGestion_rh_customer_hostess:
    path: /hostess
    defaults:
        _controller: DomiGestionRhBundle:Customer:listHostess

domiGestion_rh_customer_addHostess:
    path: /add/hostess
    defaults:
        _controller: DomiGestionRhBundle:Customer:addHostess

domiGestion_rh_customer_addClient:
    path: /add/client
    defaults:
        _controller: DomiGestionRhBundle:Customer:addClient

stanhome_rh_customer_show:
    path: /show/{id}
    methods: [GET]
    defaults:
        _controller: DomiGestionRhBundle:Customer:show

domiGestion_rh_customer_edit:
    path: /edit/{id}
    defaults:
        _controller: DomiGestionRhBundle:Customer:edit

domiGestion_rh_customer_delete:
    path: /delete/{id}
    methods: [GET]
    defaults:
        _controller: DomiGestionRhBundle:Customer:delete
