stanhome_product_brand_index:
    pattern: /
    defaults:
        _controller: StanhomeProductBundle:Brand:index

stanhome_product_brand_new:
    pattern: /new
    methods: [POST]
    defaults:
        _controller: StanhomeProductBundle:Brand:new

stanhome_product_brand_create:
    pattern: /create
    defaults:
        _controller: StanhomeProductBundle:Brand:create

stanhome_product_brand_show:
    pattern: /show/{id}
    methods: [GET]
    defaults:
        _controller: StanhomeProductBundle:Brand:show

stanhome_product_brand_edit:
    pattern: /edit/{id}
    methods: [GET]
    defaults:
        _controller: StanhomeProductBundle:Brand:edit

stanhome_product_brand_update:
    pattern: /update/{id}
    methods: [PUT]
    defaults:
        _controller: StanhomeProductBundle:Brand:update

stanhome_product_brand_delete:
    pattern: /delete/{id}
    methods: [GET]
    defaults:
        _controller: StanhomeProductBundle:Brand:delete
