stanhome_product_category_index:
    pattern: /
    methods: [GET]
    defaults:
        _controller: StanhomeProductBundle:Category:index

stanhome_product_category_new:
    pattern: /new
    defaults:
        _controller: StanhomeProductBundle:Category:new

stanhome_product_category_create:
    pattern: /create
    methods: [POST]
    defaults:
        _controller: StanhomeProductBundle:Category:create

stanhome_product_category_edit:
    pattern: /edit/{id}
    defaults:
        _controller: StanhomeProductBundle:Category:edit

stanhome_product_category_update:
    pattern: /update/{id}
    methods: [PUT]
    defaults:
        _controller: StanhomeProductBundle:Category:update

stanhome_product_category_delete:
    pattern: /delete/{id}
    methods: [GET]
    defaults:
        _controller: StanhomeProductBundle:Category:delete