stanhome_product_product_index:
   pattern: /
   methods: [GET]
   defaults:
       _controller: StanhomeProductBundle:Product:index

stanhome_product_product_new:
    pattern: /new
    defaults:
        _controller: StanhomeProductBundle:Product:new

stanhome_product_product_create:
    pattern: /create
    methods: [POST]
    defaults:
        _controller: StanhomeProductBundle:Product:create

stanhome_product_product_show:
    pattern: /show/{reference}
    defaults:
        _controller: StanhomeProductBundle:Product:show

stanhome_product_product_listbycat:
    pattern: /list/{idcat}/{catlibelle}/{idbrand}/{brandlibelle}
    defaults:
        _controller: StanhomeProductBundle:Product:list

stanhome_product_product_edit:
    pattern: /edit/{reference}
    defaults:
        _controller: StanhomeProductBundle:Product:edit

stanhome_product_product_update:
    pattern: /update/{reference}
    methods: [PUT]
    defaults:
        _controller: StanhomeProductBundle:Product:update

stanhome_product_product_delete:
    pattern: /delete/{reference}
    methods: [DELETE]
    defaults:
        _controller: StanhomeProductBundle:Product:delete
