stanhome_meeting_meeting_index:
    pattern: /
    defaults:
        _controller: StanhomeMeetingBundle:Meeting:index
        sortable: true

stanhome_meeting_meeting_new:
    pattern: /new
    defaults:
        _controller: StanhomeMeetingBundle:Meeting:new

stanhome_meeting_meeting_create:
    pattern: /create
    defaults:
        _controller: StanhomeMeetingBundle:Meeting:create

stanhome_meeting_meeting_show:
    pattern: /show/{id}
    methods: [GET]
    defaults:
        _controller: StanhomeMeetingBundle:Meeting:show

stanhome_meeting_meeting_edit:
    pattern: /edit/{id}
    methods: [GET]
    defaults:
        _controller: StanhomeMeetingBundle:Meeting:edit

stanhome_meeting_meeting_update:
    pattern: /update/{id}
    defaults:
        _controller: StanhomeMeetingBundle:Meeting:update

stanhome_meeting_meeting_delete:
    pattern: /delete/{id}
    methods: [GET]
    defaults:
        _controller: StanhomeMeetingBundle:Meeting:delete
