domiGestion_meeting_meeting_index:
    path: /
    defaults:
        _controller: DomiGestionMeetingBundle:Meeting:index
        sortable: true

domiGestion_meeting_meeting_add:
    path: /add
    defaults:
        _controller: DomiGestionMeetingBundle:Meeting:add

domiGestion_meeting_meeting_show:
    path: /show/{id}
    methods: [GET]
    defaults:
        _controller: DomiGestionMeetingBundle:Meeting:show

domiGestion_meeting_meeting_edit:
    path: /edit/{id}
    defaults:
        _controller: DomiGestionMeetingBundle:Meeting:edit

domiGestion_meeting_meeting_delete:
    path: /delete/{id}
    methods: [GET]
    defaults:
        _controller: DomiGestionMeetingBundle:Meeting:delete
