stanhome_rh_customer_import:
    resource: "@StanhomeRhBundle/Resources/config/routing/customer.yml"
    prefix: /customer

portal_search:
    pattern: /search/{fields}/{modes}/{searchString}
    methods: [GET]
    defaults:
        _controller: StanhomePortalBundle:Search:search
