<?php

namespace Proxies\__CG__\Stanhome\MeetingBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Meeting extends \Stanhome\MeetingBundle\Entity\Meeting implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'date', 'address', 'cp', 'city', 'nbPersons', 'nbKm', 'montantKm', 'montantTtc', 'montantHt', 'profit', 'customer', '' . "\0" . 'Stanhome\\MeetingBundle\\Entity\\Meeting' . "\0" . 'shopping', 'user');
        }

        return array('__isInitialized__', 'id', 'date', 'address', 'cp', 'city', 'nbPersons', 'nbKm', 'montantKm', 'montantTtc', 'montantHt', 'profit', 'customer', '' . "\0" . 'Stanhome\\MeetingBundle\\Entity\\Meeting' . "\0" . 'shopping', 'user');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Meeting $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDate($date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDate', array($date));

        return parent::setDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDate', array());

        return parent::getDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress($address)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', array($address));

        return parent::setAddress($address);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', array());

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setCp($cp)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCp', array($cp));

        return parent::setCp($cp);
    }

    /**
     * {@inheritDoc}
     */
    public function getCp()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCp', array());

        return parent::getCp();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity($city)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', array($city));

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', array());

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbPersons($nbPersons)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbPersons', array($nbPersons));

        return parent::setNbPersons($nbPersons);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbPersons()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbPersons', array());

        return parent::getNbPersons();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbKm($nbKm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbKm', array($nbKm));

        return parent::setNbKm($nbKm);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbKm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbKm', array());

        return parent::getNbKm();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantKm($montantKm)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantKm', array($montantKm));

        return parent::setMontantKm($montantKm);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantKm()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantKm', array());

        return parent::getMontantKm();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantTtc($montantTtc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantTtc', array($montantTtc));

        return parent::setMontantTtc($montantTtc);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantTtc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantTtc', array());

        return parent::getMontantTtc();
    }

    /**
     * {@inheritDoc}
     */
    public function setMontantHt($montantHt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMontantHt', array($montantHt));

        return parent::setMontantHt($montantHt);
    }

    /**
     * {@inheritDoc}
     */
    public function getMontantHt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMontantHt', array());

        return parent::getMontantHt();
    }

    /**
     * {@inheritDoc}
     */
    public function setProfit($profit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProfit', array($profit));

        return parent::setProfit($profit);
    }

    /**
     * {@inheritDoc}
     */
    public function getProfit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProfit', array());

        return parent::getProfit();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomer(\Stanhome\RhBundle\Entity\Customer $customer = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomer', array($customer));

        return parent::setCustomer($customer);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomer', array());

        return parent::getCustomer();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\Stanhome\UserBundle\Entity\User $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($user));

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getInlineAddress()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInlineAddress', array());

        return parent::getInlineAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function addShopping(\Stanhome\ShoppingBundle\Entity\Shopping $shopping)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addShopping', array($shopping));

        return parent::addShopping($shopping);
    }

    /**
     * {@inheritDoc}
     */
    public function removeShopping(\Stanhome\ShoppingBundle\Entity\Shopping $shopping)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeShopping', array($shopping));

        return parent::removeShopping($shopping);
    }

    /**
     * {@inheritDoc}
     */
    public function getShopping()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShopping', array());

        return parent::getShopping();
    }

}
