stanhome_rh_customer_index:
    path: /
    defaults:
        _controller: StanhomeRhBundle:Customer:index

stanhome_rh_customer_new:
    path: /new
    defaults:
        _controller: StanhomeRhBundle:Customer:new

stanhome_rh_customer_create:
    path: /create
    methods: [POST]
    defaults:
        _controller: StanhomeRhBundle:Customer:create

stanhome_rh_customer_show:
    path: /show/{id}
    methods: [GET]
    defaults:
        _controller: StanhomeRhBundle:Customer:show

stanhome_rh_customer_edit:
    path: /edit/{id}
    methods: [GET]
    defaults:
        _controller: StanhomeRhBundle:Customer:edit

stanhome_rh_customer_update:
    path: /update/{id}
    methods: [POST]
    defaults:
        _controller: StanhomeRhBundle:Customer:update

#stanhome_rh_customer_delete:
#    path: /delete/{id}
#    methods: [GET]
#    defaults:
#        _controller: StanhomeRhBundle:Customer:delete
