stanhome_product_product_import:
    resource: "@StanhomeProductBundle/Resources/config/routing/product.yml"
    prefix: /product

stanhome_product_brand_import:
    resource: "@StanhomeProductBundle/Resources/config/routing/brand.yml"
    prefix: /brand

stanhome_product_category_import:
    resource: "@StanhomeProductBundle/Resources/config/routing/category.yml"
    prefix: /category
